---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/hyagoo75/ebookrendaextra.com.br
    - npm install
    - npm run build
    - /bin/cp -r dist/* $DEPLOYPATH
    - rm -rf ~/public_html/*
    - cp -r dist/* ~/public_html